# Generated by Django 5.0 on 2023-12-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell"), ("SPLIT", "Split")],
                        max_length=5,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price_per_share", models.FloatField(blank=True, null=True)),
                ("trade_date", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
        ),
    ]
